[package]
authors = ["bakape <bakape@gmail.com>"]
categories = ["wasm"]
description = "client"
edition = "2018"
name = "client"
readme = "README.md"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.32"
backtrace = "0.3.50"
base64 = "0.12.3"
bincode = "1.3.1"
common = {path = "../common"}
console_error_panic_hook = "0.1.6"
flate2 = "1.0.16"
futures = "0.3.5"
hex = "0.4.2"
js-sys = "0.3.44"
serde = {version = "1.0.115", features = ["rc"]}
serde_json = "1.0.57"
uuid = "0.8.1"
wasm-bindgen = "0.2.67"
wasm-bindgen-futures = "0.4.17"
yew = "0.17.3"
indexmap = "1.6.1"

[dependencies.web-sys]
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'Node',
  "NodeList",
  "console",
  "CloseEvent",
  "ErrorEvent",
  "MessageEvent",
  "WebSocket",
  "Location",
  "Navigator",
  "EventTarget",
  "AddEventListenerOptions",
  "Event",
  "Storage",
  "Crypto",
  "SubtleCrypto",
  "CryptoKey",
  "CryptoKeyPair",
  "BinaryType",
  "FormData",
  "HtmlFormElement",
  "HtmlAnchorElement",
  "HtmlAudioElement",
  "UrlSearchParams",
  "History",
  "ScrollRestoration",
  "DomTokenList",
  "Selection",
  "HtmlInputElement",
  "HtmlTextAreaElement",
  "CssStyleDeclaration",
  "DragEvent",
  "Response",
]
version = "0.3.44"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4"]
