name: Build
on: [push, pull_request]

jobs:
  build-dev-image:
    name: Build and push dev image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Generate Docker tags
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: bakape/shamichan-dev
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          pull: true
          push: true
          cache-from: type=registry,ref=bakape/shamichan-dev
          cache-to: type=inline
          file: Dockerfile.dev
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build-dev-image
    if: success()
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Create DB
        run: >
          psql
          postgres://postgres:postgres@localhost:5432/postgres
          -c "create database shamichan;"
      - name: Build dev image
        run: >
          DOCKER_BUILDKIT=1 docker build
          --cache-from bakape/shamichan-dev
          -t shamichan
          -f Dockerfile.dev
          .
      - name: Run Rust tests
        run: >
          docker run
          --rm
          --network host
          -e CI=true
          -e TEST_DB="postgres://postgres:postgres@localhost:5432/shamichan"
          --entrypoint=""
          shamichan
          cargo test
      # TODO: move to imager workflow
      # - name: Run Go tests
      #   run: >
      #     docker run \
      #       --rm \
      #       --network host \
      #       -e CI=true \
      #       -e TEST_DB="postgres://postgres:postgres@localhost:5432/shamichan" \
      #       --entrypoint="" \
      #       shamichan \
      #       go test --race ./..
  build-prod-image:
    name: Build and push prod image
    runs-on: ubuntu-latest
    needs:
      - build-dev-image
      - test
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Generate Docker tags
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: bakape/shamichan
          tags: |
            master
            latest
            type=sha
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          pull: true
          push: true
          cache-from: |
            type=registry,ref=bakape/shamichan-dev
            type=registry,ref=bakape/shamichan
          file: Dockerfile
